### ISSUE TITLE
Back up solution (BAM vs scripts vs other)

### ISSUE THREAD

**Issue by btopro** [psudug/nittany-vagrant#12]
https://www.drupal.org/project/backup_migrate and anything else that helps w/ ensuring there isn't failure; investigate and propose a solution kid ;)

**Comment by jpat14** [comment]
drush ard --destination=/var/www/site/backups/example.tar will archive all files, db config and code into one archive. This may be a better solution than BAM for the simple fact of not requiring an added module. Backing up core is optional as well. Perhaps give a choice to the user.

**Comment by btopro** [comment]
would be good to have a bash script this is rolled into that could be automatically hooked into cron or at least tell people how they could do that to have a legit backup solution after running a few commands. @bradallenfisher might have some ideas here of how we could have the provisioner or a "golive.sh" kind of script that would trip this one and automatically apply things the server its being deployed on to provide a backup solution (local so not disaster recovery level stuff but better then nothing)

**Comment by jpat14** [comment]
Instead of having the script edit the crontab, I decided a better method would be having the ability to call the backup script from cron. You can pass it a directory to backup to, or it defaults to /vagrant/backups.

Format for the cron entry (for a backup at 2am each morning):
0 2 \* \* \* /path/to/script/drush-backup.sh /optional/argument/to/backup_path

**Comment by baf139** [comment]
I think we can close this issue in favor of adding backups to the wizard.
